// Generated by CoffeeScript 1.7.1
(function() {
  var admin, init, nconf, winston;

  init = require("fb-custom-init");

  nconf = require('nconf');

  winston = require('winston');

  admin = require("magma-admin");

  admin.command();

}).call(this);

//# sourceMappingURL=admin.map
