// Generated by CoffeeScript 1.7.1
(function() {
  var fixture, init, nconf, winston;

  init = require("fb-custom-init");

  nconf = require('nconf');

  winston = require('winston');

  fixture = require("magma-fixture");

  fixture.command();

}).call(this);

//# sourceMappingURL=fixture.map
