// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    var allcoffee, allmodules, bumps, fbumps, fm, module;
    allmodules = [];
    bumps = ["package.json"];
    fm = "node_modules/magma-";
    fbumps = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = allmodules.length; _i < _len; _i++) {
        module = allmodules[_i];
        _results.push("" + fm + "-" + module + "/package.json");
      }
      return _results;
    })();
    bumps = bumps.concat(fbumps);
    allcoffee = ["*.coffee", "routes/*.coffee", "" + fm + "*/lib/*.coffee", "" + fm + "*/test/*.coffee"];
    grunt.initConfig({
      pkg: grunt.file.readJSON("package.json"),
      coffeelint: {
        all: allcoffee
      },
      simplemocha: {
        all: {
          src: ["" + fm + "*/test/*.coffee"],
          options: {
            globals: ['should'],
            timeout: 5000,
            ignoreLeaks: false,
            ui: 'bdd',
            reporter: 'tap'
          }
        }
      },
      bumpup: bumps
    });
    grunt.loadNpmTasks("grunt-coffeelint");
    grunt.loadNpmTasks('grunt-bumpup');
    grunt.loadNpmTasks('grunt-simple-mocha');
    return grunt.registerTask("default", ["simplemocha"]);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.map
