// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, express, http, init, magma_rendering, nconf, path, routes, winston, ws;

  init = require("fb-custom-init");

  nconf = require('nconf');

  winston = require('winston');

  express = require("express");

  routes = require("./routes");

  ws = require("./routes/webservice");

  http = require("http");

  path = require("path");

  app = express();

  magma_rendering = require('magma-rendering');

  app.set("port", 23088);

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.disable('x-powered-by');

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/f/view.get/:id", magma_rendering.checkRequisite, magma_rendering.checkUserAuthorisation, ws.viewget);

  app.put("/f/view.put/:id", ws.viewput);

  app.post("/f/view.post/:id", ws.viewpost);

  app["delete"]("/f/view.del/:id", ws.viewdel);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Magma listening on port " + app.get("port"));
  });

}).call(this);

//# sourceMappingURL=live.map
