// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var magma_rendering;

  magma_rendering = require('magma-rendering');

  exports.viewget = function(req, res) {
    return magma_rendering.viewget(req, res);
  };

  exports.viewput = function(req, res) {
    return magma_rendering.viewput(req, res);
  };

  exports.viewpost = function(req, res) {
    return magma_rendering.viewpost(req, res);
  };

  exports.viewdel = function(req, res) {
    return magma_rendering.viewdel(req, res);
  };

}).call(this);

//# sourceMappingURL=webservice.map
